import { FormEvent, useEffect, useState } from 'react';
import { Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { api, clearSession, isAuthenticated } from './api';
import type { Item } from './types';

function Shell({ children }: { children: React.ReactNode }) {
  const navigate = useNavigate();
  return <div className="app-shell"><header className="topbar"><NavLink to="/" className="brand"><span className="brand-mark">✦</span> feature<span>pilot</span></NavLink><nav><NavLink to="/dashboard">Dashboard</NavLink><NavLink to="/items">Meine Features</NavLink></nav><button className="avatar" aria-label="Abmelden" onClick={() => { clearSession(); navigate('/login'); }}>FP</button></header><main>{children}</main><footer>Feature Pilot <span>•</span> Ideen werden Realität.</footer></div>;
}

function Login() {
  const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await api.login(email, password); navigate('/dashboard'); } catch (e) { setError(e instanceof Error ? e.message : 'Anmeldung fehlgeschlagen.'); } finally { setBusy(false); } }
  return <div className="auth-page"><div className="auth-card"><div className="auth-logo"><span className="brand-mark">✦</span><b>feature<span>pilot</span></b></div><p className="eyebrow">WILLKOMMEN ZURÜCK</p><h1>Deine Ideen warten.</h1><p className="muted">Melde dich an und bring deine nächsten Features auf den Weg.</p><form onSubmit={submit}><label>E-Mail-Adresse<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="du@beispiel.de" /></label><label>Passwort<input required minLength={6} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" /></label>{error && <div className="alert error">{error}</div>}<button className="primary full" disabled={busy}>{busy ? 'Wird angemeldet …' : 'Anmelden'} <span>→</span></button></form><p className="hint">Noch kein Konto? <a href="#">Jetzt registrieren</a></p></div></div>;
}

function Dashboard() { const [items, setItems] = useState<Item[]>([]); const [error, setError] = useState(''); useEffect(() => { api.listItems().then(setItems).catch(e => setError(e.message)); }, []); return <Shell><section className="hero"><div><p className="eyebrow">DEIN WORKSPACE</p><h1>Gute Ideen. <em>Große Wirkung.</em></h1><p>Verwalte deine Produktideen und verwandle sie in die nächsten großen Features.</p></div><NavLink className="primary" to="/items/new">+ Neue Idee</NavLink></section>{error && <div className="alert error">{error}</div>}<section className="stats"><div><strong>{items.length}</strong><span>Ideen gesamt</span></div><div><strong>{items.filter(i => i.description).length}</strong><span>Mit Beschreibung</span></div><div><strong>∞</strong><span>Möglichkeiten</span></div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">AKTIVITÄT</p><h2>Deine neuesten Ideen</h2></div><NavLink to="/items">Alle ansehen →</NavLink></div>{items.length === 0 ? <EmptyState /> : <div className="item-list">{items.slice(0, 5).map(item => <ItemRow key={item.id} item={item} />)}</div>}</section></Shell>; }

function ItemRow({ item }: { item: Item }) { return <NavLink to={`/items/${item.id}`} className="item-row"><span className="item-icon">✦</span><span><b>{item.title}</b><small>{item.description || 'Noch keine Beschreibung'}</small></span><time>{new Date(item.created_at).toLocaleDateString('de-DE')}</time><span>→</span></NavLink>; }
function EmptyState() { return <div className="empty"><span>✦</span><h3>Noch keine Ideen</h3><p>Starte jetzt und halte deine erste Produktidee fest.</p><NavLink className="secondary" to="/items/new">Erste Idee erstellen</NavLink></div>; }

function Items() { const [items, setItems] = useState<Item[]>([]); const [error, setError] = useState(''); const load = () => api.listItems().then(setItems).catch(e => setError(e.message)); useEffect(load, []); return <Shell><section className="page-heading"><div><p className="eyebrow">WORKSPACE</p><h1>Meine Features</h1><p>Alle Ideen an einem Ort.</p></div><NavLink className="primary" to="/items/new">+ Neue Idee</NavLink></section>{error && <div className="alert error">{error}</div>}<section className="panel"><div className="item-list">{items.length ? items.map(item => <ItemRow key={item.id} item={item} />) : <EmptyState />}</div></section></Shell>; }
function NewItem() { const navigate = useNavigate(); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { await api.createItem({ title, description }); navigate('/items'); } catch (e) { setError(e instanceof Error ? e.message : 'Speichern fehlgeschlagen.'); } finally { setBusy(false); } } return <Shell><section className="form-page"><p className="eyebrow">NEUES FEATURE</p><h1>Eine Idee nimmt Form an.</h1><p className="muted">Beschreibe deine Idee, damit sie den nächsten Schritt machen kann.</p><form className="panel form" onSubmit={submit}><label>Titel<input required maxLength={200} value={title} onChange={e => setTitle(e.target.value)} placeholder="z. B. Dunkelmodus für die App" /></label><label>Beschreibung <span className="optional">OPTIONAL</span><textarea rows={6} value={description} onChange={e => setDescription(e.target.value)} placeholder="Was soll dieses Feature können?" /></label>{error && <div className="alert error">{error}</div>}<div className="actions"><NavLink className="secondary" to="/items">Abbrechen</NavLink><button className="primary" disabled={busy}>{busy ? 'Wird gespeichert …' : 'Idee speichern'} →</button></div></form></section></Shell>; }
function Protected({ children }: { children: React.ReactNode }) { return isAuthenticated() ? <>{children}</> : <Navigate to="/login" replace />; }
export default function App() { return <Routes><Route path="/login" element={<Login />} /><Route path="/" element={<Navigate to="/dashboard" replace />} /><Route path="/dashboard" element={<Protected><Dashboard /></Protected>} /><Route path="/items" element={<Protected><Items /></Protected>} /><Route path="/items/new" element={<Protected><NewItem /></Protected>} /><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes>; }
